
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::435912838140:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-8E6BOR815K7R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::435912838140:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T08:23:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1704"
  uid: 0c770403-e0c5-49af-bbae-5b9544893ebb
