apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::435912838140:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-F2G4ICV3MNRG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::435912838140:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T15:20:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 325deea1-cb4a-49ac-b11e-66c7def109e2
