apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  labels:
    app: hello-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-flask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        # image: IMAGE_TAG
        image: santa007/hello-flask
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
